# Image for building stage
FROM node:20-alpine 

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# install Dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Expose application port
EXPOSE 5000

# RUN npm run db:push

# Start The Application
CMD [ "npm" , "run" , "start:dev" ]
